import type { Metadata } from "next";
import "./globals.css";


import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      // Aquí colocas las variables de font si las necesitas en CSS:
      className={`${GeistSans.variable} ${GeistMono.variable}`}
    >
      {/* Al body le pones la clase que inyecta NextFont */}
      <body className={`${GeistSans.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
